# Generated by Django 4.0.5 on 2022-07-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('address', models.TextField(max_length=100)),
                ('message', models.TextField(max_length=150)),
            ],
        ),
    ]
